version: '3'
services:
    php:
        container_name: app
        build: docker
        restart: always
        volumes:
            - ./docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - .:/var/www/html
        working_dir: /var/www/html
    composer:
        container_name: composer
        build: composer
        volumes:
            - .:/var/www/html
        command: composer update
